version: '3.8'

services:
  db:
    container_name: postgres-rust-api-sample
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rust-api-sample
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data:
